# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FindNeighbors_Rcpp <- function(i, X_loc, Y_loc, platform) {
    .Call(`_BACT_FindNeighbors_Rcpp`, i, X_loc, Y_loc, platform)
}

ComputePottsDist_Rcpp <- function(tmpBeta, c_vec, X_loc, Y_loc, platform) {
    .Call(`_BACT_ComputePottsDist_Rcpp`, tmpBeta, c_vec, X_loc, Y_loc, platform)
}

ComputePottsDist_sc_Rcpp <- function(tmpBeta, c_vec, X_loc, Y_loc, neighbor_indices) {
    .Call(`_BACT_ComputePottsDist_sc_Rcpp`, tmpBeta, c_vec, X_loc, Y_loc, neighbor_indices)
}

UpdateClIds <- function(dpAlpha, pottsBeta, psi1, psi2, geoq, Pi, dpXi, clIds, L1_Ids, L2_Ids, X_loc, Y_loc, platform) {
    .Call(`_BACT_UpdateClIds`, dpAlpha, pottsBeta, psi1, psi2, geoq, Pi, dpXi, clIds, L1_Ids, L2_Ids, X_loc, Y_loc, platform)
}

UpdateClIds_sc <- function(dpAlpha, pottsBeta, psi1, psi2, geoq, Pi, dpXi, clIds, L1_Ids, L2_Ids, X_loc, Y_loc, neighbor_indices) {
    .Call(`_BACT_UpdateClIds_sc`, dpAlpha, pottsBeta, psi1, psi2, geoq, Pi, dpXi, clIds, L1_Ids, L2_Ids, X_loc, Y_loc, neighbor_indices)
}

